import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { SiLeetcode } from "react-icons/si";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
// import code from "../public/code.png";
// import design from "../public/design.png";
// import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import docmedp from "../public/docmed.png";
import docmed2 from "../public/docmed2.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Khabir Ahmed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/drive/folders/13u4No5SStZnxdYe7kQH0TMIIaozVyY68"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Khabir Ahmed
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              "Hi, I'm Khabir Ahmed - a Full Stack Web Developer crafting
              seamless web experiences."
            </h3>
            <p>
              Passionate about building intuitive and scalable web applications.
              Experienced with React.js, MERN Stack, and API integrations.
              Strong problem-solving skills.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Let's connect!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/khabir-ahmed-00169822b/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/khabirahmed29">
                <AiFillGithub />
              </a>
              <a href="https://leetcode.com/u/khabir_ahmed/">
                <SiLeetcode />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Frontend: React.js, Redux, JavaScript , HTML, CSS UI <br />
              Libraries: Tailwind CSS <br />
              Backend : Node.js, Express.js, MongoDb <br />
              Git, GitHub Tools & <br />
              Others: Webpack, REST API, Postman, Axios
            </p>
          </div>
        </section>
        {/* <section>
          <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
        </section> */}
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <h4 className="text-3xl py-1 dark:text-white ">
              Full Stack Project
            </h4>
            <h3 className="text-2xl py-1 dark:text-white ">
              <a href="https://github.com/khabirahmed29/DOC-MED"> Docmed</a>
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Docmed is a full-stack medical appointment management system
              designed to streamline healthcare services. It allows patients to
              book appointments, doctors to manage their schedules, and admins
              to oversee the entire system. The platform features secure
              authentication, real-time notifications, and an intuitive user
              interface. Built with React.js for the frontend, Node.js &
              Express.js for the backend, and MongoDB for the database, Docmed
              ensures a seamless experience for both patients and healthcare
              providers.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Docmed is built using React.js, Redux, Ant Design, Axios
              (Frontend), Node.js, Express.js, JWT (Backend), and MongoDB
              (Database) for a seamless medical appointment management system.
              🚀
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap ">
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={docmedp}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={docmed2}
              />
            </div>
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
